version: 2.1

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo ${NO_ENV}
      - run: echo "failed"
          when: on_fail
            
workflows:
  my_workflow:
    jobs:
      - my_job